
version: '3.8'

services:

  rasa-run-server:
    build:
      context: ./chatbot
      dockerfile: chatbot.dockerfile
    ports:
      - "5005:5005" 
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
      - APP_BASE_URL=http://localhost:5056
    volumes:
      - ./chatbot:/app
    command: run --enable-api --cors '*' --debug

  rasa-action-server:
    build:
      context: ./chatbot
      dockerfile: actions.dockerfile
    ports:
      - "5055:5055"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
      - APP_BASE_URL=http://localhost:5056
    volumes:
       - ./chatbot/actions:/app/actions
       - ./chatbot/google_drive:/app/google_drive
    command: ["run", "actions", "--debug"]

  registro_ventas:
    build:
      context: ./registro_ventas
      dockerfile: registro_ventas.dockerfile
    environment:
      - APP_BASE_URL=http://localhost:5056
    ports:
      - "5056:5056"